config/routes.rb
Rails.application.routes.draw do

  

  resources :profiles
	devise_for :companies, controllers: { sessions: 'companies/sessions' , registrations: 'companies/registrations' } 
	devise_for :administrators 
	devise_for :users
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	resources :folders, only: [:new, :create, :show, :index] do
	resources :steps, only: [:show, :update], controller: 'folder/steps'
	end
	resources :documents, only: [:index, :new, :create, :destroy]
  	resources :offers
  	resources :blogs
  	resources :contacts, only: [:new, :create]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get "/diary" => "pages#problems", as: "my-diary"
	get "/profile" => "pages#profile", as: "carpeta_laboral"
	get "/education" => "pages#education", as: "education"
	get "/test" => "pages#test", as: "test"
	get "/terminos_condiciones" => "pages#terminos_condiciones", as: "terminos_condiciones"
	get "/politicas" => "pages#politicas", as: "politicas"
	get "/nosotros" => "pages#us", as: "nosotros"
	get "/works" => "pages#works", as: "como_funciona_empresa"
	get "/works_candidato" => "pages#works_candidato", as: "como_funciona_candidato"
	get "/faq" => "pages#faq", as: "faq_empresa"
	get "/faq_candidato" => "pages#faq_candidato", as: "faq_candidato"
	root to: "pages#home"

end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user, optional: :true  
  validates :nombre, presence: true 
  validates :contenido, presence: true   
  
end

app/models/city.rb
class City < ApplicationRecord
has_many :users, class_name: "User", foreign_key: "user_id", dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    validates :nombre, presence: true
    validates :rut, presence: true
  	validates :telefono,presence: true
    validates :direccion,presence: true
    validates :nit,presence: true
    validates :sector,presence: true
    validates :nombre_representante,presence: true
    has_many :offers, dependent: :destroy
    mount_uploader :rut, AttachmentUploader
    
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :phone, :validate => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Mensaje de #{name}",
      :to => "werk.comunicacion@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :users, dependent: :destroy	
end

app/models/document.rb
class Document < ApplicationRecord
	mount_uploader :document, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :name, presence: true # Make sure the owner's name is present.
end

app/models/folder.rb
class Folder < ApplicationRecord
	belongs_to :user
	mount_uploader :referencia_laboral,AttachmentUploader
    mount_uploader :soporte_estudios,AttachmentUploader
    mount_uploader :certificado_formacion, AttachmentUploader
	mount_uploader :fotocopia_cedula,AttachmentUploader	
	mount_uploader :referencia_laboral,AttachmentUploader
    mount_uploader :formato_domiciliaria,AttachmentUploader
    mount_uploader :formato_complemento, AttachmentUploader
	mount_uploader :conflicto_intereses,AttachmentUploader	
	mount_uploader :certificado_cuenta_bancaria,AttachmentUploader
    mount_uploader :fondo_pension,AttachmentUploader
    mount_uploader :cesantias,AttachmentUploader
	mount_uploader :certificado_eps,AttachmentUploader
	mount_uploader :oferta,AttachmentUploader
	mount_uploader :certificado_eps,AttachmentUploader
	mount_uploader :oferta,AttachmentUploader
	mount_uploader :arl,AttachmentUploader
	mount_uploader :radicacion_eps,AttachmentUploader

	cattr_accessor :form_steps do
  	%w(etapa1 etapa2 etapa3 etapa4 etapa5 etapa6)
  end

  attr_accessor :form_step
  	validates :referencia_laboral,:soporte_estudios,:referencia_laboral,:certificado_formacion, presence: true, if: -> { required_for_step?(:etapa1) }
  	validates :formato_domiciliaria, :formato_complemento,:conflicto_intereses, presence: true, if: -> { required_for_step?(:etapa2) }
  	validates :certificado_cuenta_bancaria,:fondo_pension, :cesantias,:certificado_eps, presence: true, if: -> { required_for_step?(:etapa3) }
  	validates :acepta_contrato, presence: true, if: -> {required_for_step?(:etapa5)}
  	validates :arl,:radicacion_eps, presence: true, if: -> {required_for_step?(:etapa6)}
  
		def required_for_step?(step)
	  # All fields are required if no form step is present
	  return true if form_step.nil?
	  return true if self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
	end
		
end

app/models/offer.rb
class Offer < ApplicationRecord
   
   belongs_to :company
   validates :tipo, presence: true
   validates :nombre_cargo, presence: true
   validates :tipo_contrato, presence: true
   validates :salario_float, presence: true
   validates :objetivo, presence: true
   validates :educacion_minima, presence: true
   validates :experiencia, presence: true
   validates :idiomas, presence: true
   validates :programas, presence: true
   validates :conocimientos_especificos, presence: true
   validates :disponibilidad_viajar, presence: true
   validates :disponibilidad_residencia, presence: true
   validates :vacantes, presence: true

end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
                     
		  validates :celular, :presence => {:message => ' no es valido el # de celular!'},
                     :numericality => true,
                     :length => { :minimum => 7, :maximum => 10 }
		  validates :nombres, presence: true
		  validates :apellidos, presence: true
  		validates :numero_documento,presence: true
      validates :tipo_documento,presence: true

      has_many :blogs, dependent: :destroy
      has_many :folders, dependent: :destroy
      
     # Tells rails to use this uploader for this model.
      belongs_to :city
      belongs_to :department
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/process_helper.rb
module ProcessHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Werk | encuentra tu trabajo ideal</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:200,400" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', async: Rails.env.production?, cache: Rails.env.production? %>
    <%= render 'shared/favicon' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <style type="text/css">
    .st0 {
        stroke-width: 50;
        stroke-linecap: round;
        stroke-miterlimit: 10;
        stroke-linejoin: miter;
    }

    .st1 {
        stroke-width: 50;
        stroke-miterlimit: 10;
        fill:none;stroke:#E5E25A;
    }
    .tech{
        background: #102f41;
        width: 100%;
        height: 100%;
    }
    </style>
</head>

<body>
    <div class="loader-wrap tech">
        <div class="pin">
            <div class="visual-container">
                <svg viewBox="0 0 563 800" class="stroke-lines on">
                    <path class="st0" fill="none" stroke="#fff" stroke-linejoin="bevel" stroke-miterlimit="10" d="M80.18,464.98h380.93c0,0,5.27-213.53-197.71-213.53c-63.34,0-123.43,23.96-159.48,77.69
        c-51.68,77.04-47.84,179.78-6.19,260.28c27.9,53.93,77.17,94.17,138.44,101.93c9.03,1.14,18.13,1.66,27.23,1.66
        c115.84,0,165.25-52.04,185.13-92.6" />
                </svg>
                <svg viewBox="0 0 563 800" class="stroke-lines paralax on">
                    <path class="st0" fill="none" stroke="#cfe3db" stroke-linejoin="bevel" stroke-miterlimit="10" d=
                    "M80.18,464.98h380.93c0,0,5.27-213.53-197.71-213.53c-63.34,0-123.43,23.96-159.48,77.69
        c-51.68,77.04-47.84,179.78-6.19,260.28c27.9,53.93,77.17,94.17,138.44,101.93c9.03,1.14,18.13,1.66,27.23,1.66
        c115.84,0,165.25-52.04,185.13-92.6" />
        <line class="st1" x1="26.88" y1="63.85" x2="496.85" y2="63.85"/>

                </svg>
                <div class="loader_text">
                </div>
            </div>
        </div>
    </div>
    <div id="main">
        <%= render 'shared/navbar' unless @disable_nav %>
        <%= render 'shared/message' %>
        <div id="wrapper">

            <div class="content">
                <div id="jijs" class="imagen_abajo">
                        <%= image_tag("1x/logo.png") %>
                        </div>
                <%= yield %>


            </div>
        </div>
        <footer>
        </footer>
        <a class="to-top" style="display: none;"><i class="fa fa-angle-up"></i></a>
    </div>
</body>
<script>

</script>
</html>

app/views/shared/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

app/views/shared/_footer.html.erb
<style type="text/css">
    p.comment {
        font-size: 12px;
        color: #fff;
        float: left;
        padding: 6px 12px;
        background: rgba(255, 255, 255, 0.11);
        border-radius: 6px;
        overflow: hidden;
        font-weight: 700;
        margin-bottom: 10px;
    }

    .email_subs {
        float: left;
        width: 100%;
        background: #fff;
        height: 40px;
        line-height: 40px;
        border-radius: 4px;
        padding: 0 15px;
        box-sizing: border-box;
        border: 1px solid rgba(255, 255, 255, 0.21);
        margin-top: 20px;
    }

    .button_subs {
        float: right;
        border: none;
        border-radius: 4px;
        width: 100%;
        height: 40px;
        line-height: 40px;
        color: #fff;
        margin-top: 10px;
        font-weight: 600;
        cursor: pointer;
        background: #ff5e57;
    }
</style>
<footer class="main-footer dark-footer  ">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="footer-widget fl-wrap">
                    <h3>Sobre nosotros</h3>
                    <div class="footer-contacts-widget fl-wrap">
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.</p>
                        <ul  class="footer-contacts fl-wrap">
                            <li><span><i class="fa fa-envelope-o"></i> Correo electrónico: </span><a>hackathon@unodc.com</a></li>
                            <li> <span><i class="fa fa-map-marker"></i> Dirección: </span><a>Calle Falsa 123 </a></li>
                            <li><span><i class="fa fa-phone"></i> Celular: </span><a>+(57)3182499059</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="footer-widget fl-wrap">
                    <h3>Últimas Noticias</h3>
                    <div class="widget-posts fl-wrap">
                        <ul>

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="footer-widget fl-wrap">
                    <h3>Últimos comentarios</h3>
                    <div>

                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="footer-widget fl-wrap">
                    <h3>Subscribirse</h3>
                    <div class="subscribe-widget fl-wrap">
                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.</p>
                        <div class="subcribe-form">

                        </div>
                    </div>
                    <div class="footer-widget fl-wrap">
                        <div class="footer-menu fl-wrap">
                            <ul>
                                <li><a>Inicio</a></li>                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="sub-footer fl-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="about-widget">
                        <%= image_tag("logo.png") %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="copyright"> &#169; Battery Express <%=Time.now.year%>.  Todos los derechos reservados.</div>
                </div>
                <div class="col-md-4">
                    <div class="footer-social">
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.29.0/sweetalert2.all.min.js"></script>
<header class="main-header dark-header fs-header sticky">
    <div class="header-inner">
        <div class="logo-holder">
            <%= link_to root_path do %>
            <%= image_tag("werk-logo.png") %>
            <% end %>
        </div>
        <a class="add-list" onclick="mostrar()">Buscar empleo<span></span></a>
        <div class="nav-holder main-menu">
            <nav>
                <ul>
                    <% if user_signed_in? %>
                    <li>
                        <a><%= current_user.nombres %> <%= current_user.apellidos %><i class="fa fa-caret-down"></i></a>
                        <ul>
                            <li>
                                <%= link_to "Perfil", edit_user_registration_path %>
                            </li>
                            <li>
                                <%= link_to "Procesos", edit_user_registration_path %>
                            </li>
                            <li>
                                <%= link_to 'Crear carpeta laboral', folders_path, method: :create %>
                            </li>
                            <li>
                             <%= link_to "Blog", "/blogs" %>
                            </li>
                            
                            <li>
                                <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, data: { confirm: '¿Deseas cerrar sesion?' }%>
                            </li>
                        </ul>
                    </li>
                    <% else %>
                    <li>
                        <%= link_to "Nosotros", "/nosotros" %>
                    </li>
                    <li>
                        <a>Cómo funciona</a>
                        <ul>
                            <li>
                                <%= link_to "Empresa", "/works" %>
                            </li>
                            <li>
                                <%= link_to "Candidato", "/works_candidato" %>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a>FAQ</a>
                        <ul>
                            <li>
                                <%= link_to "Empresa", "/faq" %>
                            </li>
                            <li>
                                <%= link_to "Candidato", "/faq_candidato" %>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <%= link_to new_contact_path do %>
                        Contacto
                        <% end %>
                    </li>
                    <li>
                        <%= link_to new_user_session_path do %>
                        Iniciar sesión
                        <% end %>
                    </li>
                    <% end %>
                </ul>
            </nav>
        </div>
        <div class="nav-button-wrap color-bg">
            <div class="nav-button">
                <span></span><span></span><span></span>
            </div>
        </div>
    </div>
</header>
<script type="text/javascript">
function clickButton() {
    swal({
        title: '¿Deseas cerrar sesion?',
        text: "click para confirmar",
        type: 'warning',
        showCancelButton: true,
        showConfirmButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Sí',
        cancelButtonText: 'No'
    }).then((result) => {
  if (result.value) {
    cambiar();
  }
})
}

function cambiar() {
    location.href= '../users/sign_out'
}
</script>