config/routes.rb
Rails.application.routes.draw do

  

  resources :profiles
	devise_for :companies, controllers: { sessions: 'companies/sessions' , registrations: 'companies/registrations' } 
	devise_for :administrators 
	devise_for :users
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	resources :folders, only: [:new, :create, :show, :index] do
	resources :steps, only: [:show, :update], controller: 'folder/steps'
	end
	resources :documents, only: [:index, :new, :create, :destroy]
  	resources :offers
  	resources :blogs
  	resources :contacts, only: [:new, :create]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get "/diary" => "pages#problems", as: "my-diary"
	get "/profile" => "pages#profile", as: "carpeta_laboral"
	get "/education" => "pages#education", as: "education"
	get "/test" => "pages#test", as: "test"
	get "/terminos_condiciones" => "pages#terminos_condiciones", as: "terminos_condiciones"
	get "/politicas" => "pages#politicas", as: "politicas"
	get "/nosotros" => "pages#us", as: "nosotros"
	get "/works" => "pages#works", as: "como_funciona_empresa"
	get "/works_candidato" => "pages#works_candidato", as: "como_funciona_candidato"
	get "/faq" => "pages#faq", as: "faq_empresa"
	get "/faq_candidato" => "pages#faq_candidato", as: "faq_candidato"
	root to: "pages#home"

end

app/models/offer.rb
class Offer < ApplicationRecord
   
   belongs_to :company
   validates :tipo, presence: true
   validates :nombre_cargo, presence: true
   validates :tipo_contrato, presence: true
   validates :salario_float, presence: true
   validates :objetivo, presence: true
   validates :educacion_minima, presence: true
   validates :experiencia, presence: true
   validates :idiomas, presence: true
   validates :programas, presence: true
   validates :conocimientos_especificos, presence: true
   validates :disponibilidad_viajar, presence: true
   validates :disponibilidad_residencia, presence: true
   validates :vacantes, presence: true

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
   before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!, except: [:index]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create

    @offer = Offer.new(offer_params)
    @offer.company_id = current_company.id



    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'La oferta de trabajo fue creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'La oferta de trabajo fue actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'La oferta de trabajo fue eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:tipo, :nombre_cargo, :tipo_contrato, :salario_float, 
        :objetivo, :educacion_minima, :experiencia, :idiomas, :programas, :conocimientos_especificos, 
        :disponibilidad_viajar, :disponibilidad_residencia, :vacantes, :salario, :company_id)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_with(model: offer, local: true) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container registro sign-in-container">
    <h2>Crear contrato</h2>
    <div class="tabs-container">
      <div class="tab">
        <div id="tab-1" class="tab-content">
          
          <div class="custom-form">

                     <div class="row">
                  <div class="col-md-6">
                 <label>Oferta</label>
                  <%= f.select :tipo, options_for_select([["Publico", "Publico"],["Privado", "Privado"]]), {:prompt => "Oferta"}, {:class => "chosen-select", required: true} %> 
                </div>

                    <div class="col-md-6">
                  <div class="field">
                    <label>Nombre del cargo</label>
                    <%= f.text_field :nombre_cargo %>
                  </div>
                </div>
                
              </div>

             <div class="row">
                  <div class="col-md-6">       
                  <label>Contrato</label>   
                  <%= f.select :tipo_contrato, options_for_select([["Fijo", "Fijo"],["Prestación de servicios", "Prestación de servicios"],["Indefinido", "Indefinido"],["Temporal", "Temporal"],["Aprendizaje", "Aprendizaje"]]), {:prompt => "Tipo de contrato"}, {:class => "chosen-select", required: true} %> 
                </div>

                    <div class="col-md-6">
                  <div class="field">
                    <label>Salario</label>
                    <%= f.number_field :salario_float  %>
                  </div>
                </div>
              </div>

                <div class="row">
                  <div class="col-md-12">
                  <label>Objetivo</label>
                  <%= f.text_area :objetivo  %> 
                </div>
                </div>
                <br>

                 <div class="row">
                  <div class="col-md-12">
                  <label>Requisitos</label>
                </div>
                </div>
                <br>

                <div class="row">
                  <div class="col-md-12">
                 <%= f.select :educacion_minima, options_for_select([["Universitario", "Universitario"],["Especialización", "Especialización"],["Bachiller", "Bachiller"],["Ninguna", "Ninguna"],["Maestria", "Maestria"]]), {:prompt => "Educación mínima"}, {:class => "chosen-select", required: true} %> 
                </div>
                </div>

                <div class="row">
                  <div class="col-md-6">
                <div class="field">
                    <label>Años de experiencia</label>
                    <%= f.number_field :experiencia  %>
                  </div>
                </div>


                <div class="col-md-6">
                 
                   <label>Cantidad de vacantes</label>
                      <%= f.number_field :vacantes  %>
                </div> 
                </div>

                  <div class="row">
                  <div class="col-md-6">
                 <%= f.select :idiomas, options_for_select([["Inglés", "Inglés"],["Francés", "Francés"],["Portugues", "Portugues"],["Mandarin", "Mandarin"]]), {:prompt => "Idiomas"}, {:class => "chosen-select", required: true} %>                
                </div>
                <div class="col-md-6">
                 <%= f.select :programas, options_for_select([["Ingenieria", "Ingenieria"], ["Diseño " , "Diseño"]]), {:prompt => "Programas"}, {:class => "chosen-select", required: true} %>
                </div> 
                </div>

                <div class="row">
                  <div class="col-md-12">
                 <%= f.select :conocimientos_especificos, options_for_select([["programación", "programación"],["diseño", "diseño"],["analitica", "analitica"]]), {:prompt => "Conocimientos especificos"}, {:class => "chosen-select", required: true} %>              
                </div>
                </div>

                <div class="row checkboxes">
                  <div class="col-md-6">
                    <%= f.check_box :disponibilidad_viajar  %>         

                    <label>Disponibilidad para viajar</label>
                </div>
                <div class="col-md-6">
                 <%= f.check_box :disponibilidad_residencia  %>
                   <label>Disponibilidad para cambiar de residencia</label>                      
                </div> 

                </div>




                <div class="row">
                <div class="col-md-8 col-md-offset-4">
                  <button type="submit" class="log-submit-btn">
                    <span>Crear contenido</span>
                  </button>
                </div>
              </div>



              <% end %>

app/views/offers/edit.html.erb
<h1>Actualizar</h1>

<%= render 'form', offer: @offer %>

app/views/offers/index.html.erb
<div class="oferta">
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Nombre cargo</th>
      <th>Tipo contrato</th>
      <th>Salario</th>
      <th>Objetivo</th>
      <th>Educacion minima</th>
      <th>Experiencia</th>
      <th>Idiomas</th>
      <th>Programas</th>
      <th>Conocimientos especificos</th>
      <th>Disponibilidad viajar</th>
      <th>Disponibilidad residencia</th>
      <th>Vacantes</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.tipo %></td>
        <td><%= offer.nombre_cargo %></td>
        <td><%= offer.tipo_contrato %></td>
        <td><%= offer.salario_float %></td>
        <td><%= offer.objetivo %></td>
        <td><%= offer.educacion_minima %></td>
        <td><%= offer.experiencia %></td>
        <td><%= offer.idiomas %></td>
        <td><%= offer.programas %></td>
        <td><%= offer.conocimientos_especificos %></td>
        <td><%= offer.disponibilidad_viajar %></td>
        <td><%= offer.disponibilidad_residencia %></td>
        <td><%= offer.vacantes %></td>
       
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/offers/new.html.erb
<%= render 'form', offer: @offer %>

app/views/offers/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<div class="oferta">
<p>
  <%= @offer.tipo %>
</p>

<p>
  <%= @offer.nombre_cargo %>
</p>

<p>
  <strong>Tipo contrato:</strong>
  <%= @offer.tipo_contrato %>
</p>

<p>
  <strong>Salario :</strong>
  <%= @offer.salario_float %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @offer.objetivo %>
</p>

<p>
  <strong>Educacion minima:</strong>
  <%= @offer.educacion_minima %>
</p>

<p>
  <strong>Experiencia:</strong>
  <%= @offer.experiencia %>
</p>

<p>
  <strong>Idiomas:</strong>
  <%= @offer.idiomas %>
</p>

<p>
  <strong>Programas:</strong>
  <%= @offer.programas %>
</p>

<p>
  <strong>Conocimientos especificos:</strong>
  <%= @offer.conocimientos_especificos %>
</p>

<p>
  <strong>Disponibilidad viajar:</strong>
  <%= @offer.disponibilidad_viajar %>
</p>

<p>
  <strong>Disponibilidad residencia:</strong>
  <%= @offer.disponibilidad_residencia %>
</p>

<p>
  <strong>Vacantes:</strong>
  <%= @offer.vacantes %>
</p>


<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

</div>